### PR TITLE
refactor: add fallback to reading from env when loading config

### PR DESCRIPTION
**Pull request by ovasdi**
This is a followup to https://github.com/artsy/joule/pull/126. In that PR I erroneously proclaimed that "_Joule does not break after upgrading artsy/cli to the latest version_". This was wrong. It does break and as it currently stands in joule staging some commands do not work.

Screen Shot 2023-05-04 at 9 23 50 AM

This is a proposal PR to modify the config loader by adding a fallback to read from ENV when a JSON config file is not present and values are instead set in the environment. As is done in Joule, a project managed via Hokusai.

### CODE REVIEW

**Review by jonallured — APPROVED** [review]
LGTM!! 🎉

**Review by dblandin — APPROVED** [review]
LGTM.

Aside: I noticed that the OpsGenie API token is missing from this Config class. Looks like it's always fetched from the environment and ignores the JSON file-backed config.

**Comment by ovasdi** [comment]
> LGTM.
> 
> Aside: I noticed that the OpsGenie API token is missing from this Config class. Looks like it's always fetched from the environment and ignores the JSON file-backed config.

Not anymore.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v1.6.0`](https://github.com/artsy/cli/releases/tag/v1.6.0) :rocket:

**Pull request merged**
